-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 09:22:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdd_rest_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_rest_api
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `bdd_rest_api` DEFAULT CHARACTER SET utf8 ;
USE `bdd_rest_api` ;

-- -----------------------------------------------------
-- Table `bdd_rest_api`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rest_api`.`School` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `zip` INT NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rest_api`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rest_api`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `sexe` ENUM('Homme', 'Femme') NOT NULL DEFAULT 'Homme',
  `date-naissance` DATETIME NOT NULL,
  `type` ENUM('Intervenant', 'Studiant') NOT NULL DEFAULT 'Studiant',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastLogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `attempt` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rest_api`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rest_api`.`Faculty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `nb_studient` INT NOT NULL,
  `diploma` TINYINT NOT NULL,
  `nb_year` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `School_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Faculty_School_idx` (`School_id` ASC),
  CONSTRAINT `fk_Faculty_School`
    FOREIGN KEY (`School_id`)
    REFERENCES `bdd_rest_api`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_rest_api`.`Users_has_Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_rest_api`.`Users_has_Faculty` (
  `Users_id` INT NOT NULL,
  `Faculty_id` INT NOT NULL,
  PRIMARY KEY (`Users_id`, `Faculty_id`),
  INDEX `fk_Users_has_Faculty_Faculty1_idx` (`Faculty_id` ASC),
  INDEX `fk_Users_has_Faculty_Users1_idx` (`Users_id` ASC),
  CONSTRAINT `fk_Users_has_Faculty_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `bdd_rest_api`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Faculty_Faculty1`
    FOREIGN KEY (`Faculty_id`)
    REFERENCES `bdd_rest_api`.`Faculty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
